/**
 * Structured data, injected live.
 *
 * The schemas are generated by the API from the shop's current config, so a
 * price changed in the admin panel is reflected in the structured data on the
 * next page load — there is no second copy to go stale.
 */
import { apiGet, apiUrl } from './api'

const TAG_ID = 'bbais-jsonld'

export async function injectSchemas(slug) {
  try {
    const { schemas } = await apiGet(`/api/shops/${encodeURIComponent(slug)}/seo/schemas`)
    if (!Array.isArray(schemas) || !schemas.length) return
    let tag = document.getElementById(TAG_ID)
    if (!tag) {
      tag = document.createElement('script')
      tag.id = TAG_ID
      tag.type = 'application/ld+json'
      document.head.appendChild(tag)
    }
    // One @graph rather than fourteen tags: same meaning, one parse.
    tag.textContent = JSON.stringify({ '@context': 'https://schema.org', '@graph': schemas })
  } catch {
    // Structured data is an enhancement; never let it break the page.
  }
}

/** Point the installable app at this shop's own manifest and icons. */
export function linkManifest(slug, theme) {
  const set = (rel, href, extra = {}) => {
    let el = document.querySelector(`link[rel="${rel}"]`)
    if (!el) {
      el = document.createElement('link')
      el.rel = rel
      document.head.appendChild(el)
    }
    el.href = href
    for (const [k, v] of Object.entries(extra)) el.setAttribute(k, v)
  }
  const s = encodeURIComponent(slug)
  set('manifest', apiUrl(`/api/shops/${s}/manifest.json`), { crossorigin: 'use-credentials' })
  set('icon', apiUrl(`/api/shops/${s}/icon-192.png`), { sizes: '192x192', type: 'image/png' })
  set('apple-touch-icon', apiUrl(`/api/shops/${s}/icon-192.png`))

  let meta = document.querySelector('meta[name="theme-color"]')
  if (!meta) {
    meta = document.createElement('meta')
    meta.name = 'theme-color'
    document.head.appendChild(meta)
  }
  meta.content = theme?.accent || theme?.base || '#000000'
}

/** Register the offline shell. Failure is silent: it is an enhancement. */
export function registerServiceWorker() {
  if (!('serviceWorker' in navigator)) return
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch(() => {})
  })
}
